'use client'

import { createContext, useContext } from 'react'

const NonceContext = createContext<string | undefined>(undefined)

export function NonceProvider({
  nonce,
  children,
}: {
  nonce?: string
  children: React.ReactNode
}) {
  return (
    <NonceContext.Provider value={nonce}>
      {children}
    </NonceContext.Provider>
  )
}

export function useNonce() {
  return useContext(NonceContext)
}

/**
 * Server-side helper to get nonce from headers
 * Call this in server components to access the nonce generated by middleware
 */
export async function getNonce(): Promise<string | undefined> {
  const { headers } = await import('next/headers')
  const headersList = await headers()
  return headersList.get('x-nonce') || undefined
}
