import { headers } from 'next/headers'

/**
 * Server-side helper to get nonce from headers
 * Call this in server components to access the nonce generated by middleware
 *
 * @returns The nonce value or undefined if not set
 */
export async function getNonce(): Promise<string | undefined> {
  const headersList = await headers()
  return headersList.get('x-nonce') || undefined
}
